<?php
/** @var string $content */
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hotels</title>
    <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
</head>

<body>
<div id='content'>
    <div id="container" class="container-fluid">
        <?= $content; ?>
    </div>
</div>
</body>
</html>
